// <auto-generated>
//     Generated by `Hx.Runner.Cli errorcodes render` from errorcodes/registry.json.
//     Do NOT edit by hand — append to the registry and re-render. `errorcodes check` freezes the shipped set.
// </auto-generated>
using Hx.Tooling.Contracts;

namespace Hx.Cli.Kernel;

/// <summary>The registry-backed error codes (the stable, structured <c>&lt;PREFIX&gt;&lt;NNNN&gt;</c> keys) + the manifest.</summary>
public static class ErrorCodes
{
    public const string Internal_Unhandled = "INT0001";
    public const string Usage_InvalidArguments = "USG0001";
    public const string Validation_Failed = "VAL0001";
    public const string Integrity_VerificationFailed = "ITG0001";
    public const string Validation_ToolAssetUnavailable = "VAL0002";
    public const string Integrity_ToolArchiveHashMismatch = "ITG0002";
    public const string Integrity_ToolExecutableHashMismatch = "ITG0003";
    public const string Internal_ToolDownloadFailed = "INT0002";
    public const string Validation_ToolStoreVersionUnavailable = "VAL0003";
    public const string Validation_ToolStoreVersionTooNew = "VAL0004";
    public const string Integrity_ToolStoreHashMismatch = "ITG0004";
    public const string Internal_ToolStorePopulateFailed = "INT0003";
    public const string Validation_PrerequisiteMissing = "VAL0005";
    public const string Validation_PrerequisiteUnsupportedVersion = "VAL0006";
    public const string Validation_PrerequisiteDirectoryUnavailable = "VAL0007";
    public const string Validation_PrerequisiteInstallNotApproved = "VAL0008";
    public const string Validation_PrerequisiteWingetUnavailable = "VAL0009";
    public const string Validation_PrerequisiteWingetFailed = "VAL0010";
    public const string Integrity_PrerequisiteManifestUntrusted = "ITG0005";
    public const string Validation_DotiTaskFileMissing = "VAL0011";
    public const string Validation_DotiTaskFileEmpty = "VAL0012";
    public const string Validation_DotiTaskIdDuplicate = "VAL0013";
    public const string Validation_DotiTaskUnchecked = "VAL0014";
    public const string Validation_DotiTaskHashMissing = "VAL0015";
    public const string Validation_DotiTaskHashMismatch = "VAL0016";
    public const string Validation_CycleTransitionBlocked = "VAL0017";
    public const string Validation_ReleaseTrainInvalid = "VAL0018";
    public const string Validation_ReleaseDocumentationStale = "VAL0019";
    public const string Validation_HxConfigMissing = "VAL0020";
    public const string Validation_LocalReleaseDirectoryInvalid = "VAL0021";
    public const string Validation_InstallerTargetMissing = "VAL0022";
    public const string Integrity_ManagedAssetModified = "ITG0006";
    public const string Integrity_ObsoleteRemovalBlocked = "ITG0007";
    public const string Integrity_VelopackArtifactMissing = "ITG0008";
    public const string Integrity_DotiPayloadDrift = "ITG0009";
    public const string Integrity_PayloadRootMissing = "ITG0010";
    public const string Integrity_PayloadDescriptorInvalid = "ITG0011";
    public const string Integrity_DotiRepoPayloadAhead = "ITG0012";
    public const string Integrity_ReleaseArtifactContainsSource = "ITG0013";
    public const string Validation_TaskOutOfOrder = "VAL0023";
    public const string Integrity_ProfileGateMissingConfig = "ITG0014";
    public const string Validation_UrlBlocked = "VAL0024";
    public const string Validation_BugFixUnbound = "VAL0025";
    public const string Validation_BugAssessmentMissing = "VAL0026";
    public const string Validation_ConvergeInput = "VAL0027";
    public const string Validation_CycleRefreshRerunRequired = "VAL0028";
    public const string Validation_CycleRefreshNotBound = "VAL0029";
    public const string Validation_SentruxStructuralReviewRequired = "VAL0030";
    public const string Validation_SentruxRebaselineRefused = "VAL0031";
    public const string Validation_ReleaseTrainDrift = "VAL0032";

    /// <summary>The full manifest — code metadata used by <see cref="Diag"/> to build diagnostics.</summary>
    public static readonly IReadOnlyList<ErrorCodeEntry> All =
    [
        new("INT0001", "internal", "INT", 1, Severity.Error, ExitClass.Internal, "internal.unhandled",
            "An unhandled internal error occurred.", "This is a bug — report it with the command and inputs."),
        new("USG0001", "usage", "USG", 1, Severity.Error, ExitClass.Usage, "usage.invalid-arguments",
            "Invalid command arguments.", "Run the command with --help to see valid usage."),
        new("VAL0001", "validation", "VAL", 1, Severity.Error, ExitClass.Validation, "validation.failed",
            "Validation failed.", "Fix the reported issues and re-run."),
        new("ITG0001", "integrity", "ITG", 1, Severity.Error, ExitClass.Integrity, "integrity.verification-failed",
            "An integrity verification failed.", "Re-vendor or re-verify the tool/proof; do not bypass the gate."),
        new("VAL0002", "validation", "VAL", 2, Severity.Error, ExitClass.Validation, "validation.tool-asset-unavailable",
            "No vendored-tool asset is mapped for the host RID.", "This RID has no pinned asset yet; vendor one, or run on a supported RID (win-x64)."),
        new("ITG0002", "integrity", "ITG", 2, Severity.Error, ExitClass.Integrity, "integrity.tool-archive-hash-mismatch",
            "A downloaded tool archive's SHA-256 does not match the manifest.", "Do not install the binary; re-check the pinned downloadUrl/archiveSha256 in the tool manifest."),
        new("ITG0003", "integrity", "ITG", 3, Severity.Error, ExitClass.Integrity, "integrity.tool-executable-hash-mismatch",
            "A fetched tool executable's SHA-256 does not match the manifest.", "Do not install the binary; re-check the pinned executableSha256 in the tool manifest."),
        new("INT0002", "internal", "INT", 2, Severity.Error, ExitClass.Internal, "internal.tool-download-failed",
            "A vendored-tool download or extraction failed.", "Check network connectivity and the pinned downloadUrl, then re-run the fetch."),
        new("VAL0003", "validation", "VAL", 3, Severity.Error, ExitClass.Validation, "validation.tool-store-version-unavailable",
            "The pinned tool version is not present in the shared tool store.", "Run `tools fetch` to populate the store, or reinstall `hx` via its channel (`dotnet tool update -g Heurex.SpeckitDoti`, or the Microsoft Store); the solution pins a version the store lacks."),
        new("VAL0004", "validation", "VAL", 4, Severity.Error, ExitClass.Validation, "validation.tool-store-version-too-new",
            "The solution was generated by a newer toolkit than is installed.", "Upgrade the installed toolkit/installer to match the solution's pinned versions; the tool refuses to downgrade."),
        new("ITG0004", "integrity", "ITG", 4, Severity.Error, ExitClass.Integrity, "integrity.tool-store-hash-mismatch",
            "A shared-store tool binary's SHA-256 does not match the manifest.", "Do not use the binary; run `tools fetch` to re-populate the store from a verified source, or reinstall `hx` via its channel (`dotnet tool update -g Heurex.SpeckitDoti`, or the Microsoft Store)."),
        new("INT0003", "internal", "INT", 3, Severity.Error, ExitClass.Internal, "internal.tool-store-populate-failed",
            "Populating the shared tool store failed.", "Check disk space and permissions for the configured tool-store location, then retry."),
        new("VAL0005", "validation", "VAL", 5, Severity.Error, ExitClass.Validation, "validation.prerequisite-missing",
            "A required prerequisite is missing.", "Install the missing prerequisite from the trusted next action and re-run the command."),
        new("VAL0006", "validation", "VAL", 6, Severity.Error, ExitClass.Validation, "validation.prerequisite-unsupported-version",
            "A prerequisite was found but its version is not supported.", "Install a supported version from the trusted prerequisite instructions and re-run the command."),
        new("VAL0007", "validation", "VAL", 7, Severity.Error, ExitClass.Validation, "validation.prerequisite-directory-unavailable",
            "A required directory is unavailable.", "Fix the output, repository, temp, cache, or payload directory before re-running the command."),
        new("VAL0008", "validation", "VAL", 8, Severity.Error, ExitClass.Validation, "validation.prerequisite-install-not-approved",
            "A prerequisite install plan was not approved.", "Review the exact install plan and re-run with the matching --confirm-plan digest only if approved."),
        new("VAL0009", "validation", "VAL", 9, Severity.Error, ExitClass.Validation, "validation.prerequisite-winget-unavailable",
            "Windows Package Manager is unavailable.", "Install or enable winget, or use the trusted manual prerequisite instructions."),
        new("VAL0010", "validation", "VAL", 10, Severity.Error, ExitClass.Validation, "validation.prerequisite-winget-failed",
            "Windows Package Manager failed to install a prerequisite.", "Review the winget result, install the prerequisite manually if needed, and re-run the prerequisite check."),
        new("ITG0005", "integrity", "ITG", 5, Severity.Error, ExitClass.Integrity, "integrity.prerequisite-manifest-untrusted",
            "The trusted prerequisite manifest is missing or invalid.", "Use a verified speckit-doti release payload; do not use repo-local install sources."),
        new("VAL0011", "validation", "VAL", 11, Severity.Error, ExitClass.Validation, "validation.doti-task-file-missing",
            "The active Doti task file is missing.", "Create or restore the active feature task file, then re-run the Doti task hash or gate command."),
        new("VAL0012", "validation", "VAL", 12, Severity.Error, ExitClass.Validation, "validation.doti-task-file-empty",
            "The active Doti task file contains no required tasks.", "Add required Markdown task entries before completing the implementation gate."),
        new("VAL0013", "validation", "VAL", 13, Severity.Error, ExitClass.Validation, "validation.doti-task-id-duplicate",
            "A Doti task id appears more than once.", "Give each task a unique id before stamping task hashes."),
        new("VAL0014", "validation", "VAL", 14, Severity.Error, ExitClass.Validation, "validation.doti-task-unchecked",
            "A required Doti task is not checked.", "Complete the task, check it in the task ledger, and re-run `doti task-hash stamp`."),
        new("VAL0015", "validation", "VAL", 15, Severity.Error, ExitClass.Validation, "validation.doti-task-hash-missing",
            "A checked Doti task is missing its canonical hash marker.", "Run `doti task-hash stamp` after every required task is complete."),
        new("VAL0016", "validation", "VAL", 16, Severity.Error, ExitClass.Validation, "validation.doti-task-hash-mismatch",
            "A checked Doti task hash no longer matches the canonical task content.", "Review the task text change, then re-run `doti task-hash stamp` only after the task is still complete."),
        new("VAL0017", "validation", "VAL", 17, Severity.Error, ExitClass.Validation, "validation.cycle-transition-blocked",
            "A Doti stage-transition commit is blocked.", "Fix the reported scope, gate, task-hash, or freshness blocker before starting the next Doti stage."),
        new("VAL0018", "validation", "VAL", 18, Severity.Error, ExitClass.Validation, "validation.release-train-invalid",
            "The Doti release train is invalid.", "Repair or complete every included feature cycle before running the release path."),
        new("VAL0019", "validation", "VAL", 19, Severity.Error, ExitClass.Validation, "validation.release-documentation-stale",
            "Release-facing documentation is stale for the release train.", "Update README, CHANGELOG, or relevant documentation with the included feature slugs before release."),
        new("VAL0020", "validation", "VAL", 20, Severity.Error, ExitClass.Validation, "validation.hx-config-missing",
            "The required executable-adjacent hx.config.json file is missing.", "Use a verified hx installation or restore hx.config.json next to hx.exe before running operational commands."),
        new("VAL0021", "validation", "VAL", 21, Severity.Error, ExitClass.Validation, "validation.local-release-directory-invalid",
            "The configured local release directory is invalid.", "Set localReleaseOutput.directory in hx.config.json to an absolute path, or disable local release output."),
        new("VAL0022", "validation", "VAL", 22, Severity.Error, ExitClass.Validation, "validation.installer-target-missing",
            "The installer or Doti install target repository argument is missing.", "Pass the explicit target repository directory; the command does not default to the current directory."),
        new("ITG0006", "integrity", "ITG", 6, Severity.Error, ExitClass.Integrity, "integrity.managed-asset-modified",
            "A managed Doti asset has been modified from its canonical baseline.", "Review the modified path and use --force only when replacing local customization is intended."),
        new("ITG0007", "integrity", "ITG", 7, Severity.Error, ExitClass.Integrity, "integrity.obsolete-removal-blocked",
            "Obsolete Doti asset removal was blocked by unproven or modified content.", "Inspect the blocked legacy path, preserve repo-owned content, or rerun with --force only when replacement is intended."),
        new("ITG0008", "integrity", "ITG", 8, Severity.Error, ExitClass.Integrity, "integrity.velopack-artifact-missing",
            "A required Velopack release artifact is missing.", "Re-run the release command so installer/update artifacts and checksums are produced and inspected."),
        new("ITG0009", "integrity", "ITG", 9, Severity.Error, ExitClass.Integrity, "integrity.doti-payload-drift",
            "Scaffold-installed Doti payload parity drift was detected.", "Run doti render-skills or repair the scaffold payload source before relying on generated repos."),
        new("ITG0010", "integrity", "ITG", 10, Severity.Error, ExitClass.Integrity, "integrity.payload-root-missing",
            "The installed payload descriptor (payload.manifest.json) is absent beside hx.", "Use a verified hx installation; the installed payload descriptor must ship beside the executable. Do not run installed commands from a source checkout."),
        new("ITG0011", "integrity", "ITG", 11, Severity.Error, ExitClass.Integrity, "integrity.payload-descriptor-invalid",
            "The installed payload descriptor is unparseable or carries an unsupported schemaVersion.", "Reinstall hx from a verified channel; the payload descriptor must be valid and integrity-anchored to the installed executable."),
        new("ITG0012", "integrity", "ITG", 12, Severity.Error, ExitClass.Integrity, "integrity.doti-repo-payload-ahead",
            "The target repo's recorded Doti payload is newer than the installed tool's.", "Upgrade the installed hx (dotnet tool update -g Heurex.SpeckitDoti, or the Microsoft Store); the tool refuses to downgrade a repo's payload."),
        new("ITG0013", "integrity", "ITG", 13, Severity.Error, ExitClass.Integrity, "integrity.release-artifact-contains-source",
            "A produced release artifact contains the tool's own build tree or a full source archive.", "Stage only the curated payload (template pack, manifests, grammars, .doti); the packaging gate refuses source in any in-scope artifact."),
        new("VAL0023", "validation", "VAL", 23, Severity.Error, ExitClass.Validation, "validation.task-out-of-order",
            "A Doti task is checked out of order (an earlier task or phase is incomplete).", "Complete tasks in document/phase order; a task may be checked only when all earlier tasks are checked."),
        new("ITG0014", "integrity", "ITG", 14, Severity.Error, ExitClass.Integrity, "integrity.profile-gate-missing-config",
            "A gate the declared tier enforces is missing or has malformed config.", "Restore the gate's configuration; an enforced gate with missing or malformed config fails closed (no delete-config bypass)."),
        new("VAL0024", "validation", "VAL", 24, Severity.Error, ExitClass.Validation, "validation.url-blocked",
            "A URL was refused by the Doti URL trust policy.", "Use an https URL on the host allowlist that does not resolve to a loopback, link-local, private, or cloud-metadata address."),
        new("VAL0025", "validation", "VAL", 25, Severity.Error, ExitClass.Validation, "validation.bug-fix-unbound",
            "A bug-cycle fix is not bound to a recorded assessment.", "Run `doti bug assess` first; the fix stage must be bound to that assessment's verdict/remediation contract."),
        new("VAL0026", "validation", "VAL", 26, Severity.Error, ExitClass.Validation, "validation.bug-assessment-missing",
            "The bug-cycle assessment for this bug is missing.", "Run `doti bug assess` to produce the read-only verdict/remediation contract before the fix or test stage."),
        new("VAL0027", "validation", "VAL", 27, Severity.Error, ExitClass.Validation, "validation.converge-input",
            "The converge command's required inputs (spec/plan/tasks) are missing or invalid.", "Ensure the active feature's spec, plan, and tasks exist before running `doti converge`."),
        new("VAL0028", "validation", "VAL", 28, Severity.Error, ExitClass.Validation, "validation.cycle-refresh-rerun-required",
            "A stale stage cannot be safely re-stamped because a real input changed; its stage command must be re-run.", "Re-run the stage's command (e.g. re-clarify/re-plan/re-analyze) to regenerate its artifact, then stamp it."),
        new("VAL0029", "validation", "VAL", 29, Severity.Error, ExitClass.Validation, "validation.cycle-refresh-not-bound",
            "A stale stage cannot be re-stamped because its produced artifact is absent.", "Re-run the stage's command to produce its artifact before stamping; refresh refuses to bind an absent artifact."),
        new("VAL0030", "validation", "VAL", 30, Severity.Error, ExitClass.Validation, "validation.sentrux-structural-review-required",
            "Two Sentrux optimization attempts stayed in the escalation band.", "Stop blind optimization; run a structural architecture review (/06-doti-arch-review) to decide functionality-driven growth (evidence-gated rebaseline) vs wrong architecture (refactor)."),
        new("VAL0031", "validation", "VAL", 31, Severity.Error, ExitClass.Validation, "validation.sentrux-rebaseline-refused",
            "A Sentrux rebaseline was refused.", "A rebaseline needs explicit operator intent AND a change-set-fresh arch-review record classifying the growth as functionality-driven; refactor instead if the architecture is wrong."),
        new("VAL0032", "validation", "VAL", 32, Severity.Error, ExitClass.Validation, "validation.release-train-drift",
            "A later release-train feature changed paths an earlier completed-unreleased feature owns or documents.", "Reconcile the cross-feature drift before release: update the earlier feature's spec/docs/code (or the later feature's), so the release train is internally consistent."),
    ];
}
