// <auto-generated>
//     Generated by `Hx.Runner.Cli errorcodes render` from errorcodes/registry.json.
//     Do NOT edit by hand — append to the registry and re-render. `errorcodes check` freezes the shipped set.
// </auto-generated>
using Hx.Tooling.Contracts;

namespace Hx.Cli.Kernel;

/// <summary>The registry-backed error codes (the stable, structured <c>&lt;PREFIX&gt;&lt;NNNN&gt;</c> keys) + the manifest.</summary>
public static class ErrorCodes
{
    public const string Internal_Unhandled = "INT0001";
    public const string Usage_InvalidArguments = "USG0001";
    public const string Validation_Failed = "VAL0001";
    public const string Integrity_VerificationFailed = "ITG0001";
    public const string Validation_ToolAssetUnavailable = "VAL0002";
    public const string Integrity_ToolArchiveHashMismatch = "ITG0002";
    public const string Integrity_ToolExecutableHashMismatch = "ITG0003";
    public const string Internal_ToolDownloadFailed = "INT0002";

    /// <summary>The full manifest — code metadata used by <see cref="Diag"/> to build diagnostics.</summary>
    public static readonly IReadOnlyList<ErrorCodeEntry> All =
    [
        new("INT0001", "internal", "INT", 1, Severity.Error, ExitClass.Internal, "internal.unhandled",
            "An unhandled internal error occurred.", "This is a bug — report it with the command and inputs."),
        new("USG0001", "usage", "USG", 1, Severity.Error, ExitClass.Usage, "usage.invalid-arguments",
            "Invalid command arguments.", "Run the command with --help to see valid usage."),
        new("VAL0001", "validation", "VAL", 1, Severity.Error, ExitClass.Validation, "validation.failed",
            "Validation failed.", "Fix the reported issues and re-run."),
        new("ITG0001", "integrity", "ITG", 1, Severity.Error, ExitClass.Integrity, "integrity.verification-failed",
            "An integrity verification failed.", "Re-vendor or re-verify the tool/proof; do not bypass the gate."),
        new("VAL0002", "validation", "VAL", 2, Severity.Error, ExitClass.Validation, "validation.tool-asset-unavailable",
            "No vendored-tool asset is mapped for the host RID.", "This RID has no pinned asset yet; vendor one, or run on a supported RID (win-x64)."),
        new("ITG0002", "integrity", "ITG", 2, Severity.Error, ExitClass.Integrity, "integrity.tool-archive-hash-mismatch",
            "A downloaded tool archive's SHA-256 does not match the manifest.", "Do not install the binary; re-check the pinned downloadUrl/archiveSha256 in the tool manifest."),
        new("ITG0003", "integrity", "ITG", 3, Severity.Error, ExitClass.Integrity, "integrity.tool-executable-hash-mismatch",
            "A fetched tool executable's SHA-256 does not match the manifest.", "Do not install the binary; re-check the pinned executableSha256 in the tool manifest."),
        new("INT0002", "internal", "INT", 2, Severity.Error, ExitClass.Internal, "internal.tool-download-failed",
            "A vendored-tool download or extraction failed.", "Check network connectivity and the pinned downloadUrl, then re-run the fetch."),
    ];
}
