using System.Text;
using System.Text.Json;
using Hx.Tooling.Contracts;

namespace Hx.Cli.Kernel;

/// <summary>A frozen shipped code: the stable contract (code ⇄ name ⇄ exit class) that must never change.</summary>
public sealed record ShippedCode(string Code, string Name, string ExitClass);

/// <summary>
/// The error-code registry engine. <see cref="Load"/> turns the single-source
/// <c>errorcodes/registry.json</c> into the numbered <see cref="ErrorCodeEntry"/> set (per-category sequential
/// number → code <c>&lt;PREFIX&gt;&lt;NNNN&gt;</c>, name <c>&lt;category&gt;.&lt;suffix&gt;</c>);
/// <see cref="RenderConstants"/> regenerates <c>ErrorCodes.g.cs</c>; <see cref="CheckStability"/> enforces the
/// append-only freeze against <c>errorcodes/shipped.json</c>.
/// </summary>
public static class ErrorCodeRegistry
{
    private static readonly JsonSerializerOptions Options = new(JsonSerializerDefaults.Web);

    private sealed record CategoryDto(string Prefix, string ExitClass);
    private sealed record CodeDto(string Category, string Suffix, string Severity, string Message, string Remediation);
    private sealed record RegistryDto(int SchemaVersion, Dictionary<string, CategoryDto> Categories, List<CodeDto> Codes);
    private sealed record ShippedDto(int SchemaVersion, List<ShippedCode> Codes);

    /// <summary>Parse <c>registry.json</c> into the numbered code set (the order of <c>codes</c> assigns the per-category number).</summary>
    public static IReadOnlyList<ErrorCodeEntry> Load(string registryJsonPath)
    {
        RegistryDto dto = JsonSerializer.Deserialize<RegistryDto>(File.ReadAllText(registryJsonPath), Options)
            ?? throw new InvalidOperationException("registry.json is empty or not a JSON object.");

        Dictionary<string, int> counters = [];
        List<ErrorCodeEntry> entries = [];
        foreach (CodeDto code in dto.Codes)
        {
            if (!dto.Categories.TryGetValue(code.Category, out CategoryDto? category))
            {
                throw new InvalidOperationException($"Code '{code.Suffix}' references unknown category '{code.Category}'.");
            }

            int number = counters.TryGetValue(code.Category, out int n) ? n + 1 : 1;
            counters[code.Category] = number;
            entries.Add(new ErrorCodeEntry(
                $"{category.Prefix}{number:D4}", code.Category, category.Prefix, number,
                Enum.Parse<Severity>(code.Severity), Enum.Parse<ExitClass>(category.ExitClass),
                $"{code.Category}.{code.Suffix}", code.Message, code.Remediation));
        }

        return entries;
    }

    /// <summary>Load the frozen shipped baseline (<c>errorcodes/shipped.json</c>).</summary>
    public static IReadOnlyList<ShippedCode> LoadShipped(string shippedJsonPath) =>
        (JsonSerializer.Deserialize<ShippedDto>(File.ReadAllText(shippedJsonPath), Options)
            ?? throw new InvalidOperationException("shipped.json is empty or not a JSON object.")).Codes;

    /// <summary>
    /// The append-only stability check: every shipped code must still exist with the same name and
    /// exit class. New codes are allowed; removing or mutating a shipped one is a violation. Returns the violations.
    /// </summary>
    public static IReadOnlyList<string> CheckStability(IReadOnlyList<ErrorCodeEntry> current, IReadOnlyList<ShippedCode> shipped)
    {
        Dictionary<string, ErrorCodeEntry> byCode = current.ToDictionary(e => e.Code, StringComparer.Ordinal);
        List<string> violations = [];
        foreach (ShippedCode s in shipped)
        {
            if (!byCode.TryGetValue(s.Code, out ErrorCodeEntry? entry))
            {
                violations.Add($"shipped code {s.Code} ({s.Name}) was removed");
                continue;
            }

            if (entry.Name != s.Name)
            {
                violations.Add($"shipped code {s.Code} name changed: '{s.Name}' -> '{entry.Name}'");
            }

            if (entry.ExitClass.ToString() != s.ExitClass)
            {
                violations.Add($"shipped code {s.Code} exit class changed: {s.ExitClass} -> {entry.ExitClass}");
            }
        }

        return violations;
    }

    /// <summary>Regenerate the <c>ErrorCodes.g.cs</c> source (LF newlines) from the numbered code set.</summary>
    public static string RenderConstants(IReadOnlyList<ErrorCodeEntry> entries)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//     Generated by `Hx.Runner.Cli errorcodes render` from errorcodes/registry.json.\n");
        sb.Append("//     Do NOT edit by hand — append to the registry and re-render. `errorcodes check` freezes the shipped set.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("using Hx.Tooling.Contracts;\n\n");
        sb.Append("namespace Hx.Cli.Kernel;\n\n");
        sb.Append("/// <summary>The registry-backed error codes (the stable, structured <c>&lt;PREFIX&gt;&lt;NNNN&gt;</c> keys) + the manifest.</summary>\n");
        sb.Append("public static class ErrorCodes\n{\n");
        foreach (ErrorCodeEntry e in entries)
        {
            sb.Append($"    public const string {ConstName(e.Name)} = \"{e.Code}\";\n");
        }

        sb.Append("\n    /// <summary>The full manifest — code metadata used by <see cref=\"Diag\"/> to build diagnostics.</summary>\n");
        sb.Append("    public static readonly IReadOnlyList<ErrorCodeEntry> All =\n    [\n");
        foreach (ErrorCodeEntry e in entries)
        {
            sb.Append($"        new(\"{e.Code}\", \"{e.Category}\", \"{e.Prefix}\", {e.Number}, Severity.{e.Severity}, ExitClass.{e.ExitClass}, \"{e.Name}\",\n");
            sb.Append($"            {Quote(e.Message)}, {Quote(e.Remediation)}),\n");
        }

        sb.Append("    ];\n}\n");
        return sb.ToString();
    }

    /// <summary>The C# const name for a dotted code name: <c>internal.unhandled</c> → <c>Internal_Unhandled</c>.</summary>
    public static string ConstName(string name) =>
        string.Join('_', name.Split('.').Select(segment =>
            string.Concat(segment.Split('-').Select(Capitalize))));

    private static string Capitalize(string s) => s.Length == 0 ? s : char.ToUpperInvariant(s[0]) + s[1..];

    private static string Quote(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
