// <auto-generated>
//     Generated by `Hx.Runner.Cli errorcodes render` from errorcodes/registry.json.
//     Do NOT edit by hand — append to the registry and re-render. `errorcodes check` freezes the shipped set.
// </auto-generated>
using Hx.Tooling.Contracts;

namespace Hx.Cli.Kernel;

/// <summary>The registry-backed error codes (the stable, structured <c>&lt;PREFIX&gt;&lt;NNNN&gt;</c> keys) + the manifest.</summary>
public static class ErrorCodes
{
    public const string Internal_Unhandled = "INT0001";
    public const string Usage_InvalidArguments = "USG0001";
    public const string Validation_Failed = "VAL0001";
    public const string Integrity_VerificationFailed = "ITG0001";

    /// <summary>The full manifest — code metadata used by <see cref="Diag"/> to build diagnostics.</summary>
    public static readonly IReadOnlyList<ErrorCodeEntry> All =
    [
        new("INT0001", "internal", "INT", 1, Severity.Error, ExitClass.Internal, "internal.unhandled",
            "An unhandled internal error occurred.", "This is a bug — report it with the command and inputs."),
        new("USG0001", "usage", "USG", 1, Severity.Error, ExitClass.Usage, "usage.invalid-arguments",
            "Invalid command arguments.", "Run the command with --help to see valid usage."),
        new("VAL0001", "validation", "VAL", 1, Severity.Error, ExitClass.Validation, "validation.failed",
            "Validation failed.", "Fix the reported issues and re-run."),
        new("ITG0001", "integrity", "ITG", 1, Severity.Error, ExitClass.Integrity, "integrity.verification-failed",
            "An integrity verification failed.", "Re-vendor or re-verify the tool/proof; do not bypass the gate."),
    ];
}
