namespace Hx.Tooling.Contracts.Setup;

/// <summary>
/// 029 D1: the SINGLE source of the operator-subset defaults — these are exactly the values documented in
/// <c>docs/configuration.md</c> (a test asserts parity). Every resolved key whose intent is absent reads its value
/// from here with <see cref="ConfigSource.Default"/>. Pure constants; no IO.
/// </summary>
public static class SetupConfigDefaults
{
    // ---- identity (docs/configuration.md §1) ----
    public const string Company = "Heurex";

    /// <summary>The fixed sample <c>&lt;Description&gt;</c> sentence (docs/configuration.md §1).</summary>
    public const string Description = "A sample agent-first .NET CLI generated by the Heurex scaffold.";

    /// <summary><c>&lt;Authors&gt;</c> defaults to the company value (derived). Stored marker for the show-table default.</summary>
    public const string AuthorsDefaultMarker = "(company)";

    /// <summary><c>&lt;RepositoryUrl&gt;</c> is absent in the template by default.</summary>
    public const string RepositoryUrl = "";

    public const string License = "MIT";

    // ---- versioning (docs/configuration.md §2) ----
    public const string NextVersion = "0.1.0";

    // ---- release & local output (docs/configuration.md §3) ----
    public const string ReleaseEnvironmentVariable = "DOTI_RELEASE_ROOT";
    public const bool ReleaseEnabled = true;

    /// <summary>The machine-local release directory is unset by default (docs/configuration.md §3, machine-local).</summary>
    public const string ReleaseDirectory = "";

    // ---- publishing (docs/configuration.md §4) ----
    public const bool PublishEnabled = false;
    public const string PublishOwner = "";
    public const string PublishRepo = "";
    public const string PublishWorkflow = "release.yml";
    public const string PublishEnvironment = "production";
    public const string PublishTarget = "nuget.org";

    // ---- agents (docs/configuration.md §5) ----
    public const string Agents = "codex,claude";

    // ---- constitution §2 (docs/configuration.md §7) ----
    public const string DomainPrinciples = "[DOMAIN_PRINCIPLES]";
    public const string TechStack = "[TECH_STACK]";
    public const string CodingStyle = "[CODING_STYLE]";
    public const string SecurityCompliance = "[SECURITY_COMPLIANCE]";
    public const string Performance = "[PERFORMANCE]";
}
